language: node_js

node_js:
  - "node"

dist: trusty

sudo: false

addons:
  chrome: stable

install:
  - npm --version
  - npm i

script:
  - yarn test
  - yarn build

cache:
  directories:
    - node_modules
